version: '2.1'
services:
  spark:
    #image: docker.io/bitnami/spark:3
    build: ./spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '7077:7077'
      - '8081:8080'

    volumes:
      - /opt/bitnami/spark/files:/opt/bitnami/spark/files
      - ./app:/app
  spark-worker:
    #image: docker.io/bitnami/spark:3
    build: ./spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8082:8081"
    volumes:
      - /opt/bitnami/spark/files:/opt/bitnami/spark/files
      - ./app:/app
    depends_on: 
      spark: 
        condition: service_started
  mongo:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=uninova
    ports:
      - "27018:27017"
    volumes:
      - ./mongo/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  postgres:
    container_name: postgres-db
    image: postgres:12.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: grisgris123
    ports: 
      - "5434:5432"
    volumes:
      - ./postgres/1_init_vesselai.sql:/docker-entrypoint-initdb.d/1_init_vesselai.sql
  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - CHOKIDAR_USERPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
     - 3000:3000
    volumes:
      - ./frontend/src:/frontend/src
  monetdb:
    image: monetdb/vessel_ai:latest
    ports: 
    - "50000:50000"
    environment:
      DB_NAME: vesselai
      DB_USER: uninova
      DB_PASSWORD: temppassword!
    volumes:
      - database_storage:/var/monetdb5/dbfarm
      - type: bind
        source: ./monetdb
        target: /initdbd
  app:
    build: ./app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
     - "5002:5002"
    volumes:
     - ./app:/app
     - /opt/bitnami/spark/files:/opt/bitnami/spark/files
volumes:
  database_storage: