FROM bitnami/spark:3.2.1

ARG PYTHON_VERSION=3.8.11

USER root
RUN apt update && \
    apt upgrade -y && \
    apt install -y --no-install-recommends \
    build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev \
    && rm -rf /var/lib/apt/lists/* \
    && curl -O https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz \
    && tar -xf Python-${PYTHON_VERSION}.tar.xz \
    && cd Python-${PYTHON_VERSION} \
    && ./configure --enable-optimizations \
    && make -j 4 \
    && make altinstall \
    && cd .. \
    && rm -rf Python-${PYTHON_VERSION} \
    && rm Python-${PYTHON_VERSION}.tar.xz \
    && update-alternatives --install /usr/local/bin/python python /usr/local/bin/python${PYTHON_VERSION%.*} 1 \
    && update-alternatives --install /usr/local/bin/python3 python3 /usr/local/bin/python${PYTHON_VERSION%.*} 1 \
    && rm -rf /opt/bitnami/python
USER 1001

#RUN mkdir -p "/opt/airflow/plugins"

RUN curl https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/3.0.1/mongo-spark-connector_2.12-3.0.1.jar --output /opt/bitnami/spark/jars/mongo-spark-connector_2.12-3.0.1.jar
RUN curl https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/3.12.10/mongo-java-driver-3.12.10.jar --output /opt/bitnami/spark/jars/mongo-java-driver-3.12.10.jar
RUN curl https://jdbc.postgresql.org/download/postgresql-42.3.0.jar --output /opt/bitnami/spark/jars/postgresql-42.3.0.jar
RUN curl https://www.monetdb.org/downloads/Java/monetdb-jdbc-3.3.jre8.jar --output /opt/bitnami/spark/jars/monetdb-jdbc-3.3.jre8.jar