FROM python:3.8-slim-bullseye

ENV DEBIAN_FRONTEND="noninteractive" \
    JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-11-jdk \
    curl \
  && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN \
  mkdir -p /opt/bitnami/spark/jars && \
  curl https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/3.0.1/mongo-spark-connector_2.12-3.0.1.jar \
    --output /opt/bitnami/spark/jars/mongo-spark-connector_2.12-3.0.1.jar && \
  curl https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/3.12.10/mongo-java-driver-3.12.10.jar \
    --output /opt/bitnami/spark/jars/mongo-java-driver-3.12.10.jar && \
  curl https://jdbc.postgresql.org/download/postgresql-42.3.0.jar \
    --output /opt/bitnami/spark/jars/postgresql-42.3.0.jar && \
  curl https://www.monetdb.org/downloads/Java/monetdb-jdbc-3.3.jre8.jar \
    --output /opt/bitnami/spark/jars/monetdb-jdbc-3.3.jre8.jar
    

ENTRYPOINT ["python", "main.py"]
